### PR TITLE
vgo attempt 2 issue 115

### PR DESCRIPTION
**Pull request by g-k**
Fixes: #115 ~~based off #188~~ 

NB: 

* the crypto11 problem that forced us to pin an older version was fixed in https://github.com/ThalesIgnite/crypto11/pull/10 but we should test for that issue in HSM stage
* ~~The CCI build job is failing with "go: cannot find main module; see 'go help modules'" I believe this is due to not having `go.mod` and `go.sum` published at go.mozilla.org. I think we can land this branch then replay the build and it should pass, otherwise we might need to split out monitor into its own repo.~~ edit: miles pointed out we weren't installing the local checkout

@milescrabill this might require pipeline changes to deploy monitor

r? @jvehent @milescrabill

### CODE REVIEW

**Comment by jvehent** [comment]
Do we want to get rid of the vendor directory? Specifically, how much value is there in having local copies of the dependencies? How high is the risk of one of those disappearing from the internet, which would break our builds?

**Comment by g-k** [comment]
> Do we want to get rid of the vendor directory?
> Specifically, how much value is there in having local copies of the dependencies?

The vendor dir:

* gives us diffs of updated deps (frequently too big to view in github though), which is theoretically easier to audit
* makes it easier to install and build the app without changes

vgo / 1.11 modules:

* makes easier update and pin individual packages, which could make dep change review easier (and frees us from things like the makefile hack to checkout the old crypto11 version for a known working commit)

Also, discussed some in https://github.com/mozilla-services/autograph/issues/115 

> How high is the risk of one of those disappearing from the internet, which would break our builds?

I think some downtime is acceptable. Especially if we cache built docker images in the dockerflow pipeline allowing us to redeploy existing tags, but I'd expect the risk of breakage to be the probability of the host for any single package being down at build time. 

There might be a way to have the best of both worlds and keep the module cache in the app dir.

**Comment by milescrabill** [comment]
We can use modules and still vendor our deps if we want, an approach is described here: https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/.

Essentially: `GO111MODULE=on`, `go mod vendor`, `go test -mod=vendor`, `go build -mod=vendor`

**Comment by g-k** [comment]
Closing in favor a new branch that I can be more deliberate in and cherry pick out of this branch.

**Pull request closed without merging**
